// Auto-generated by scripts/generate-showcase-audio.mjs
// Run `npm run generate:audio` whenever narration text/voice changes.

export type ShowcaseAudioTiming = {
  file: string;
  from: number;
  durationInFrames: number;
  durationSeconds: number;
  sampleRate: number;
};

export const SHOWCASE_AUDIO_TIMINGS: ShowcaseAudioTiming[] = [
  { file: "showcase-01-start.wav", from: 0, durationInFrames: 190, durationSeconds: 6.331, sampleRate: 24000 },
  { file: "showcase-02-editor.wav", from: 190, durationInFrames: 206, durationSeconds: 6.851, sampleRate: 24000 },
  { file: "showcase-03-features.wav", from: 396, durationInFrames: 358, durationSeconds: 11.931, sampleRate: 24000 },
  { file: "showcase-04-flowchart.wav", from: 754, durationInFrames: 373, durationSeconds: 12.411, sampleRate: 24000 },
  { file: "showcase-05-stack.wav", from: 1127, durationInFrames: 321, durationSeconds: 10.691, sampleRate: 24000 },
  { file: "showcase-06-end.wav", from: 1448, durationInFrames: 253, durationSeconds: 8.411, sampleRate: 24000 },
];

export const SHOWCASE_DURATION = 1701;
