// Auto-generated by scripts/generate-showcase-audio.mjs
export type ShowcaseAudioTiming = { file: string; from: number; durationInFrames: number; durationSeconds: number; sampleRate: number; };
export const SHOWCASE_AUDIO_TIMINGS: ShowcaseAudioTiming[] =[
  { file: "showcase-01-start.wav", from: 0, durationInFrames: 187, durationSeconds: 6.211, sampleRate: 24000 },
  { file: "showcase-02-editor.wav", from: 187, durationInFrames: 212, durationSeconds: 7.051, sampleRate: 24000 },
  { file: "showcase-03-youtube.wav", from: 399, durationInFrames: 224, durationSeconds: 7.451, sampleRate: 24000 },
  { file: "showcase-04-website.wav", from: 623, durationInFrames: 250, durationSeconds: 8.331, sampleRate: 24000 },
  { file: "showcase-05-upload.wav", from: 873, durationInFrames: 301, durationSeconds: 10.011, sampleRate: 24000 },
  { file: "showcase-06-examples.wav", from: 1174, durationInFrames: 252, durationSeconds: 8.371, sampleRate: 24000 },
  { file: "showcase-07-features.wav", from: 1426, durationInFrames: 297, durationSeconds: 9.891, sampleRate: 24000 },
  { file: "showcase-08-flowchart.wav", from: 1723, durationInFrames: 578, durationSeconds: 19.251, sampleRate: 24000 },
  { file: "showcase-09-stack.wav", from: 2301, durationInFrames: 360, durationSeconds: 11.971, sampleRate: 24000 },
  { file: "showcase-10-end.wav", from: 2661, durationInFrames: 276, durationSeconds: 9.171, sampleRate: 24000 },
];
export const SHOWCASE_DURATION = 2937;
